javaScripts: 
  - "javascripts/vendor/typogr.js"
  - "javascripts/custom.js"

socialNetworks:
  mastodon: "https://mastodon.design/@beseku"
  twitter: "beseku"
  
styleSheets: 
  - "stylesheets/custom.scss"
