[[redirects]]
  from = "https://www.ben.seku.co/*"
  to = "https://ben.seku.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://beseku.com/*"
  to = "https://ben.seku.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.beseku.com/*"
  to = "https://ben.seku.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://beseku.net/*"
  to = "https://ben.seku.co/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://www.beseku.net/*"
  to = "https://ben.seku.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://beseku.org/*"
  to = "https://ben.seku.co/:splat"
  status = 301
  force = true
    
[[redirects]]
  from = "https://www.beseku.org/*"
  to = "https://ben.seku.co/:splat"
  status = 301
  force = true